# db_url = "mysql://root:password@localhost/live777"

[http]
# Http Server Listen Address
# listen = "[::]:8888"
# Cross-Origin Resource Sharing (CORS)
# reference: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
# cors = false

# WHIP/WHEP auth token
# Headers["Authorization"] = "Bearer {token}"
# [auth]
# tokens = ["live777"]

# Not WHIP/WHEP standard
# https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication#basic
# Headers["Authorization"] = "Basic {Base64.encode({username}:{password})}"
# [[auth.accounts]]
# username = "live777"
# password = "live777"

[log]
# Env: `LOG_LEVEL`
# Default: info
# Values: off, error, warn, info, debug, trace
# level = "warn"

[reforward]
# When a new whep beginning, and trigger reforward, check reforward status done times
# Every times check after wait 50ms. If Mare than 5 * 50ms return error
# whep_check_frequency = 5
# Check cluster all node reforward status time interval
# Default: 3000ms (3s)
# check_tick_time = 3000
# If reforward is working, but no consumer subscription, This reforward status is: `idle`
# When status `idle` more than this time duration, close this reforward.
# Default: 10s
# maximum_idle_time = 60000
# cascade = false
