FROM rust:slim-trixie AS builder

WORKDIR /app

COPY . .

RUN cargo build --bin=whepfrom --release

FROM debian:slim-trixie

COPY --from=builder /app/target/release/whepfrom /usr/local/bin/whepfrom

CMD ["whepfrom"]
