FROM rust:slim-bookworm AS builder

WORKDIR /app

COPY . .

RUN apt update -y && apt install -y --no-install-recommends npm

RUN npm install && npm run build

RUN cargo build --bin=liveman --release

FROM debian:bookworm-slim

COPY --from=builder /app/conf/liveman.toml /etc/live777/liveman.toml
COPY --from=builder /app/target/release/liveman /usr/local/bin/liveman

CMD ["liveman"]
