FROM rust:slim-trixie AS builder

WORKDIR /app

COPY . .

RUN cargo build --bin=whipinto --release

FROM debian:trixie-slim

COPY --from=builder /app/target/release/whipinto /usr/local/bin/whipinto

CMD ["whipinto"]
