FROM rust:slim-bookworm as builder

WORKDIR /app

COPY . .

RUN cargo build --package=whepfrom --release

FROM debian:bookworm-slim

COPY --from=builder /app/target/release/whepfrom /usr/local/bin/whepfrom

CMD ["whepfrom"]
