FROM rust:slim-bookworm as builder

WORKDIR /app

COPY . .

RUN apt update -y && apt install -y --no-install-recommends npm

RUN npm install && npm run build

RUN cargo build --release

RUN cargo build --package=whipinto --release
RUN cargo build --package=whepfrom --release

FROM debian:bookworm-slim

COPY --from=builder /app/conf/liveman.toml /etc/live777/liveman.toml
COPY --from=builder /app/target/release/liveman /usr/local/bin/liveman

CMD ["liveman"]
