FROM rust:slim-bookworm as builder

WORKDIR /app

COPY . .

RUN cargo build --package=whipinto --release

FROM debian:bookworm-slim

COPY --from=builder /app/target/release/whipinto /usr/local/bin/whipinto

CMD ["whipinto"]
