name: Build Android Rust

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-linux-android
        profile: minimal
        components: rust-src

    - name: Install Android NDK
      run: |
        mkdir -p /usr/local/android-ndk
        wget https://dl.google.com/android/repository/android-ndk-r26d-linux.zip
        unzip android-ndk-r26d-linux.zip -d /usr/local/android-ndk/
        mv /usr/local/android-ndk/android-ndk-r26d /usr/local/android-ndk/r26d

    - name: Set environment variables
      run: |
        echo "NDK_PATH=/usr/local/android-ndk/r26d" >> $GITHUB_ENV
        echo "AR=$NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar" >> $GITHUB_ENV
        echo "CC_aarch64_linux_android=$NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android25-clang" >> $GITHUB_ENV
        echo "CXX_aarch64_linux_android=$NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android25-clang++" >> $GITHUB_ENV

    - name: Update .cargo/config.toml
      run: |
        sed -i 's|/usr/local/android-ndk/r26d|${{ env.NDK_PATH }}|g' .cargo/config.toml

    - name: Build
      run: cargo build --target aarch64-linux-android --release
