name: Build Android Rust Project

on:
  push:
    branches:
      - test # 或你使用的分支名称
  pull_request:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_NDK_HOME: ${{ github.workspace }}/android-ndk-r26d
      CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER: ${{ github.workspace }}/android-ndk-r26d/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android25-clang
      CARGO_TARGET_AARCH64_LINUX_ANDROID_AR: ${{ github.workspace }}/android-ndk-r26d/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-linux-android
        override: true

    - name: Download and setup Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r26d-linux.zip
        unzip android-ndk-r26d-linux.zip
        export ANDROID_NDK_HOME=$PWD/android-ndk-r26d

    - name: Build Rust project for Android
      run: cargo build --target aarch64-linux-android --release
