[package]
name = "net4mqtt"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
portpicker = "0.1.1"

[dependencies]
kcp = "0.5.3"
rumqttc = { version = "0.24.0", features = ["url"] }
rumqttd = "0.19.0"
tokio = { version = "1.40.0", features = ["rt-multi-thread"] }
tracing = { workspace = true }
config = "0.14.0"
