[package]
name = "net4mqtt"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
portpicker = "0.1.1"
rumqttd = "0.19.0"

[dependencies]
utils = { path = "../../libs/utils" }
clap = { workspace = true, features = ["derive"] }
tracing = { workspace = true }

url = "2.5.2"
kcp = "0.5.3"
rumqttc = "0.24.0"
tokio = { version = "1.40.0", features = ["rt-multi-thread", "sync"] }
